package vista;


import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author AnaLadi
 */
public class AgregaEmpledoVista extends javax.swing.JFrame {

    /**
     * Creates new form AgregaEmpledo
     */
    public AgregaEmpledoVista() {
        initComponents();
    }

    public void fecha() {
        Calendar cal = Calendar.getInstance();
        String fechas = cal.get(cal.DATE) + "/" + cal.get(cal.MONTH) + "/" + cal.get(cal.YEAR);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ap = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        am = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tip = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        nomus = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("AGREGA UN EMPLEADO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 284, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 130, 118, 17);

        ap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apKeyTyped(evt);
            }
        });
        getContentPane().add(ap);
        ap.setBounds(230, 120, 200, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 630, 89, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 210, 121, 17);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 630, 100, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nombre:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 90, 61, 17);

        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomKeyTyped(evt);
            }
        });
        getContentPane().add(nom);
        nom.setBounds(230, 80, 200, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Apellido Materno:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 170, 121, 17);

        tel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });
        getContentPane().add(tel);
        tel.setBounds(230, 200, 110, 30);

        am.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amKeyTyped(evt);
            }
        });
        getContentPane().add(am);
        am.setBounds(230, 160, 200, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Correo");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 250, 150, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Contraseña");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(60, 550, 90, 17);

        tip.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empleado", "Administrador" }));
        getContentPane().add(tip);
        tip.setBounds(240, 590, 110, 21);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Tipo de Empleado");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(60, 590, 130, 17);

        nomus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomusActionPerformed(evt);
            }
        });
        getContentPane().add(nomus);
        nomus.setBounds(230, 240, 160, 30);
        getContentPane().add(pass);
        pass.setBounds(240, 550, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int numNom = Integer.parseInt(nomina.getText());
        int eda = Integer.parseInt(ed.getText());
        int anio = Integer.parseInt(año.getSelectedItem().toString());
        int tele = Integer.parseInt(tel.getText());
        EntidadEmpleado mp = new EntidadEmpleado();
//        EntidadEmpleado mp = new EntidadEmpleado(
               mp.setNumNomina(numNom); 
               mp.setNombre(nom.getText().toUpperCase()); 
               mp.setApPaterno( ap.getText().toUpperCase());
               mp.setApMaterno(am.getText().toUpperCase()); 
               mp.setEdad(eda); 
               mp.setDia(dia.getSelectedIndex() + 1); 
               mp.setMes( mes.getSelectedIndex() + 1);
               mp.setAño(anio);  
               mp.setTelefono(tele);  
               mp.setSexo(sex.getSelectedItem().toString().toUpperCase()); 
               mp.setCalle(calle.getText().toUpperCase());
               mp.setColonia(colonia.getText().toUpperCase()); 
               mp.setMunicipio( municipio.getText().toUpperCase());
               mp.setNomUs(nomus.getText().toUpperCase()); 
               mp.setPass(pass.getText().toUpperCase());  
               mp.setTipo(tip.getSelectedIndex() + 1);
               DataEmpleados ag = new DataEmpleados();

        System.out.println("nomina" + numNom + "\nnombre" + mp.getNombre() + "\nap"
                + ap.getText() + "\n am " + am.getText() + "\ned " + eda + "\ndia " + (dia.getSelectedIndex() + 1) + "\nmes "
                + (mes.getSelectedIndex() + 1) + "\nanio " + anio + "\ntel " + tele + "\nsex " + sex.getSelectedItem().toString() + "\ncalle "
                + calle.getText() + "\ncol " + colonia.getText() + " \n mun" + municipio.getText() + "\nnomu" + nomus.getText() + "\npass"
                + pass.getText() + "\ntipo " + tip.getSelectedIndex() + 1);
        try {
            ag.insertEmpleado(mp);
            JOptionPane.showMessageDialog(null, "Empleado guardado");

        } catch (SQLException ex) {
            Logger.getLogger(AgregaEmpledoVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int anio = Integer.parseInt(año.getSelectedItem().toString());
        System.out.println(anio);
        MenuAdminVista mn = new MenuAdminVista();
        mn.setVisible(true);
        this.dispose();

        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped
 char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_telKeyTyped

    private void nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyTyped
char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); }
        // TODO add your handling code here:
    }//GEN-LAST:event_nomKeyTyped

    private void apKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apKeyTyped
char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); }
        // TODO add your handling code here:
    }//GEN-LAST:event_apKeyTyped

    private void amKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amKeyTyped

        char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); }
// TODO add your handling code here:
    }//GEN-LAST:event_amKeyTyped

    private void nomusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregaEmpledoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregaEmpledoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregaEmpledoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregaEmpledoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregaEmpledoVista().setVisible(true);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField am;
    private javax.swing.JTextField ap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nomus;
    private javax.swing.JTextField pass;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox tip;
    // End of variables declaration//GEN-END:variables
}
