/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Control.ControlProducto;
import Control.ControlProveedor;
import Entidad.EntidadMiembros;
import Entidad.EntidadProducto;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author netosolis.com
 */
public class VistaMiembros extends javax.swing.JFrame {

    private UIManager.LookAndFeelInfo apariencias[];
    private DefaultTableModel modelo = new DefaultTableModel();
    private Control.ControlMiembros mie;

    /**
     * Creates new form Main
     */
    public void cargaprod() {
        limpiarTabla();
        try {

            ResultSet rs = mie.selectMiembros();
            while (rs.next()) {
                Object row[] = new Object[6];
                for (int i = 0; i < 6; i++) {
                    row[i] = rs.getObject(i + 1);
                }
                modelo.addRow(row);

            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar los datos de la Base de Datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarMiembrosTabla() {
        limpiarTabla();
        try {

            mie = new Control.ControlMiembros();
            this.table.setModel(modelo);

            ResultSet rs = mie.selectMiembros();
            while (rs.next()) {
                Object row[] = new Object[6];
                for (int i = 0; i < 6; i++) {
                    row[i] = rs.getObject(i + 1); //El resulset los indices empiezan en 1, mi for lo empieso en 0 por eso le sumo i+1
                }

                modelo.addRow(row);

            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar los datos de la Base de Datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public VistaMiembros() {

        initComponents();
        Control.ControlProveedor cProv = new ControlProveedor();
        Control.ControlProducto prodnom = new ControlProducto();

        try {
            table.setModel(modelo);
            modelo.addColumn("NOMBRE");
            modelo.addColumn("APELLIDO PATERNO");
            modelo.addColumn("APELLIDO MATERNO");
            modelo.addColumn("TELEFONO 1");
            modelo.addColumn("TELEFONO 2");
            modelo.addColumn("CORREO");

            SwingUtilities.updateComponentTreeUI(this);

            ResultSet rs = cProv.selectProveedor();
            ResultSet rst = prodnom.selectProductoNombre();
            try {
                String produNom;
                String Prov;
                while (rst.next()) {
                    produNom = rst.getString(1);
                    cbProductos.addItem(produNom);
                }
                while (rs.next()) {
                    Prov = rs.getString(1);

                }
            } catch (SQLException ex) {
                Logger.getLogger(VistaMiembros.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.cargarMiembrosTabla();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTel2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtAPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAMaterno = new javax.swing.JTextField();
        txtTel1 = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cbProductos = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtClave2 = new javax.swing.JTextField();
        txtPrecio2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cbPeliculas1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jComboBox3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD netosolis.com");
        setResizable(false);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setEditingColumn(0);
        table.setEditingRow(0);
        jScrollPane1.setViewportView(table);

        jButton4.setText("ACTUALIZAR DATOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 427, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(113, 113, 113))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Miembros", jPanel1);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("NOMBRE:*");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("APELLIDO PATERNO:*");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("APELLIDO MATERNO:");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("TELEFONO 1:");

        txtNombre.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setToolTipText("NOMBRE DEL NUEVO MIEMBRO*OBLIGATORIO");
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                toUpper(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtTel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtTel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTel2.setToolTipText("TELEFONO DEL MIEMBRO ");
        txtTel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                toUpper(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTel2KeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jButton1.setText("Registrar Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar(evt);
            }
        });

        txtAPaterno.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtAPaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAPaterno.setToolTipText("APELLIDO PATERNO DEL MIEMBRO*OBLIGSTORIO");
        txtAPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAPaternotoUpper(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAPaternoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("TELEFONO 2:");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("CORREO:");

        txtAMaterno.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtAMaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAMaterno.setToolTipText("APELLIDO MATERNO DEL MIEMBRO");
        txtAMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAMaternotoUpper(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAMaternoKeyTyped(evt);
            }
        });

        txtTel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtTel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTel1.setToolTipText("TELEFONO DEL MIEMBRO");
        txtTel1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTel1toUpper(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTel1KeyTyped(evt);
            }
        });

        txtCorreo.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setToolTipText("CORREO DEL MIEMBRO");
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreotoUpper(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtAPaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Agregar nuevo miembro", jPanel2);

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Clave:");

        txtNombre2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombre2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre2KeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Precio:");

        jButton2.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jButton2.setText("Actualizar Pelicula");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarPelicula(evt);
            }
        });

        cbProductos.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        cbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarDatosPelicula(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Seleccion Producto:");

        txtClave2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtClave2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClave2KeyReleased(evt);
            }
        });

        txtPrecio2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtPrecio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecio2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecio2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(45, 45, 45)
                        .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtClave2)
                                    .addComponent(txtNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                    .addComponent(txtPrecio2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtClave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Modificar Producto", jPanel3);

        cbPeliculas1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("Seleccion la Pelicula:");

        jButton3.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jButton3.setText("Eliminar Pelicula");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPelicula(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(45, 45, 45)
                .addComponent(cbPeliculas1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPeliculas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(64, 64, 64)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Producto", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Funcion para actualizar los datos de una pelicula
    private void ActualizarPelicula(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarPelicula
        Entidad.EntidadProducto Eprod = new EntidadProducto();
        Control.ControlProducto cp = new ControlProducto();
        Eprod.setNombre(cbProductos.getSelectedItem().toString());
        ResultSet rs = cp.selectProdNom(Eprod);
        double pre = Double.parseDouble(txtPrecio2.getText());

        try {

            while (rs.next()) {

                Eprod.setIdProd(rs.getInt(1));

            }
            Eprod.setClave(txtClave2.getText());
            Eprod.setNombre(txtNombre2.getText());
            Eprod.setPrecio(pre);

        } catch (SQLException ex) {
            System.out.println(ex.getCause());
            Logger.getLogger(ControlProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (txtClave2.getText().trim().length() == 0 || txtNombre2.getText().trim().length() == 0 || txtPrecio2.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Falta LLenar Algunos Datos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
//        if (mie.update(Eprod)) {
//            JOptionPane.showMessageDialog(this, "Producto registrado con exito.", "Extio", JOptionPane.INFORMATION_MESSAGE);
//
//            this.cargarProducto();
//        } else {
//            JOptionPane.showMessageDialog(this, "Error al registrar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_ActualizarPelicula

    //Funcion para eliminar una pelicula
    private void EliminarPelicula(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPelicula


    }//GEN-LAST:event_EliminarPelicula

    //Funcion que carga los datos de la pelicula a actualizar
    private void CargarDatosPelicula(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarDatosPelicula
        Entidad.EntidadProducto Eprod = new EntidadProducto();
        Control.ControlProducto cp = new ControlProducto();
        Eprod.setNombre(cbProductos.getSelectedItem().toString());
        ResultSet rs = cp.selectProdNom(Eprod);
        String clave = null, nombre = null, precio = null;

        try {

            while (rs.next()) {
                clave = rs.getString(2);
                nombre = rs.getString(3);
                precio = rs.getString(4);
            }
            txtClave2.setText(clave);
            txtNombre2.setText(nombre);
            txtPrecio2.setText(precio);
        } catch (SQLException ex) {
            System.out.println(ex.getCause());
            Logger.getLogger(ControlProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CargarDatosPelicula

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.cargaprod();

    }//GEN-LAST:event_jButton4ActionPerformed


    private void Registrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar
        Entidad.EntidadMiembros Emie = new EntidadMiembros();
        while (txtNombre.getText().trim().length() == 0 || txtAPaterno.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "FALTA LLENAR ALGUNOS DATOS NECESARIOS", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtAMaterno.getText().trim().length() == 0 || txtTel1.getText().length() == 0 || txtTel2.getText().length() == 0 || txtCorreo.getText().trim().length() == 0) {
            Emie.setNombre(txtNombre.getText());
            Emie.setaPaterno(txtAPaterno.getText());
           mie.insertCorreoAmaterno(Emie);
        }
        if (rootPaneCheckingEnabled) {

        } else {

            Emie.setNombre(txtNombre.getText());
            Emie.setaPaterno(txtAPaterno.getText());
            Emie.setaMaterno(txtAMaterno.getText());
            int tel1 = Integer.parseInt(txtTel1.getText());
            Emie.setTel1(tel1);
            int tel2 = Integer.parseInt(txtTel2.getText());
            Emie.setTel2(tel2);
            Emie.setCorreo(txtCorreo.getText());
        }
//        }  if (mie.insertCompleo(Emie)) {
//            
//            JOptionPane.showMessageDialog(this, "MIEMBRO REGISTRADO", "EXITO", JOptionPane.INFORMATION_MESSAGE);
//            txtNombre.setText(null);
//            txtAPaterno.setText(null);
//            txtAMaterno.setText(null);
//            txtTel1.setText(null);
//            txtTel2.setText(null);
//            txtCorreo.setText(null);
//            this.cargarMiembrosTabla();
//        }

//        if (prod.insert(Eprod)) {
//            JOptionPane.showMessageDialog(this, "Producto registrado con exito.", "Extio", JOptionPane.INFORMATION_MESSAGE);
//            txtClave.setText("");
//            txtNombre.setText("");
//            txtPrecio.setText("0.0");
//            cbProductos.removeAllItems();
//            cbPeliculas1.removeAllItems();
//            this.cargarProducto();
//        } else {
//            JOptionPane.showMessageDialog(this, "Error al registrar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_Registrar


    private void toUpper(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toUpper
        JTextField ob = (JTextField) evt.getSource();
        ob.setText(ob.getText().toUpperCase());
        ob.setText(ob.getText().trim());
    }//GEN-LAST:event_toUpper

    private void txtAPaternotoUpper(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAPaternotoUpper
        JTextField ob = (JTextField) evt.getSource();
        ob.setText(ob.getText().toUpperCase());
        ob.setText(ob.getText().trim());
    }//GEN-LAST:event_txtAPaternotoUpper

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        Control.ControlProveedor cProv = new ControlProveedor();
        ResultSet rs = cProv.selectProveedor();
        try {
            String Prov;
            while (rs.next()) {
                Prov = rs.getString(1);
//                cbProv.addItem(Prov);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VistaMiembros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void txtAPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAPaternoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAPaternoKeyTyped

    private void txtTel2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTel2KeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTel2KeyTyped

    private void txtClave2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClave2KeyReleased
        JTextField ob = (JTextField) evt.getSource();
        ob.setText(ob.getText().toUpperCase());
        ob.setText(ob.getText().trim());
    }//GEN-LAST:event_txtClave2KeyReleased

    private void txtNombre2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre2KeyReleased
        JTextField ob = (JTextField) evt.getSource();
        ob.setText(ob.getText().toUpperCase());
        ob.setText(ob.getText().trim());

    }//GEN-LAST:event_txtNombre2KeyReleased

    private void txtNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre2KeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombre2KeyTyped

    private void txtPrecio2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecio2KeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecio2KeyTyped

    private void txtPrecio2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecio2KeyReleased
        JTextField ob = (JTextField) evt.getSource();
        ob.setText(ob.getText().trim());
    }//GEN-LAST:event_txtPrecio2KeyReleased

    private void txtAMaternotoUpper(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAMaternotoUpper
        JTextField ob = (JTextField) evt.getSource();
        ob.setText(ob.getText().toUpperCase());
        ob.setText(ob.getText().trim());
    }//GEN-LAST:event_txtAMaternotoUpper

    private void txtAMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAMaternoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAMaternoKeyTyped

    private void txtTel1toUpper(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTel1toUpper
        JTextField ob = (JTextField) evt.getSource();
        ob.setText(ob.getText().toUpperCase());
        ob.setText(ob.getText().trim());
    }//GEN-LAST:event_txtTel1toUpper

    private void txtCorreotoUpper(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreotoUpper
        JTextField ob = (JTextField) evt.getSource();
        ob.setText(ob.getText().toUpperCase());
        ob.setText(ob.getText().trim());
    }//GEN-LAST:event_txtCorreotoUpper

    private void txtTel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTel1KeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTel1KeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    //Funcion que carga todas la peliculas en la tabla y en los JCOMboBox
//    private void cargarPeliculas(){
//        limpiarTabla();
//        try{
//            ResultSet rs = crud.selectXtodas();
//            while(rs.next()){
//                Object row [] = new Object[6];
//                for (int i = 0; i < 6; i++) {
//                    row[i] = rs.getObject(i+1); //El resulset los indices empiezan en 1, mi for lo empieso en 0 por eso le sumo i+1
//                }
//                //Agregamos cada registro al modelo de la tabla
//                modelo.addRow(row);
//                cbPeliculas.addItem(new Pelicula(Integer.parseInt(row[0].toString()),row[1].toString(),row[2].toString(),
//                        row[4].toString(),row[5].toString(),Integer.parseInt(row[3].toString())));
//                cbPeliculas1.addItem(new Pelicula(Integer.parseInt(row[0].toString()),row[1].toString(),row[2].toString(),
//                        row[4].toString(),row[5].toString(),Integer.parseInt(row[3].toString())));
//            }
//        }catch(Exception e){
//            e.printStackTrace();
//             JOptionPane.showMessageDialog(this, "Error al cargar los datos de la Base de Datos.", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//    }
    //Funcion para limpiar la tabla
    private void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMiembros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbPeliculas1;
    private javax.swing.JComboBox cbProductos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtClave2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtPrecio2;
    private javax.swing.JTextField txtTel1;
    private javax.swing.JTextField txtTel2;
    // End of variables declaration//GEN-END:variables
}
